# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Cracker9 Blog
subtitle: Cracker9 tech blog
description: This site is cracker9 tech blog.
author: Cracker9
language: ko
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.cracker9.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 6
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
# date_format: MM/DD/YYYY
date_format: MM/DD/YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
- hexo-server
- hexo-generator-archive
- hexo-generator-category
- hexo-generator-index
- hexo-generator-restful
- hexo-generator-tag
- hexo-renderer-jade
- hexo-renderer-marked
- hexo-renderer-stylus
- hexo-generator-cname
- hexo-deployer-git
- hexo-generator-seo-friendly-sitemap
- hexo-autonofollow
- hexo-auto-canonical
- hexo-generator-feed
## Themes: https://hexo.io/themes/
theme: overdose

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/Cracker9/Cracker9.github.io.git
  branch: master

sitemap:
  path: sitemap.xml

# rss feed auto generator
feed:
  type: atom
  path: feed.xml
  limit: 20
  hub:

# hexo-generator-restful
restful:
  site: false
  posts_size: 3
  posts_props:
    title: true
    slug: true
    date: true
    updated: false
    comments: false
    path: false
    permalink: true
    excerpt: false
    cover: false
    content: false
    keywords: false
    categories: false
    tags: false
  categories: false
  use_category_slug: false
  tags: false
  use_tag_slug: false
  post: false
  pages: false

